<?php return array (
  'company_name' => 'media f SA',
  'contact_person' => '',
  'email' => '',
  'phone' => '',
  'city' => '',
  'state' => '',
  'zipcode' => '',
  'country_id' => '82',
  'address' => '',
  'timezone_id' => '358',
  'default_currency' => '',
  'default_currency_symbol' => '',
  'default_language' => 'fr',
  'direction' => 'ltr',
  'allowed_upload_file' => '',
  'allowed_upload_max_size' => '',
  'application_title' => 'Agendage',
  'in_time' => '09:25',
  'out_time' => '17:45',
  'logo' => '',
);